[general]
id = "countdown_example_task"
name = "Countdown Example Task"
description = "Countdown Example Task. Prints a countdown from 12 to 1."
url = "https://github.com/kpliuta/tt-sh-runner-example-task"
version = "0.1.1"
runner_id = "simple_github_sh_runner"
runner_min_version = ">=0.1.0"
default_timeout = "1m"
